### PR TITLE
Bug solving in obj file export: material path as a relative path

### PR DESCRIPTION
**Pull request by jdelanoy**
# PR Description

This solves a bug in the export of OBJ meshes: the material link was written in aboslute path in the .obj file instead of relative path. This is solved by removing all the directory structure when writing the material path in the obj (will be written in the same directory).

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by JacquesOlivierLachaud** [comment]
Seems fine. Do you mind updating the ChangeLog file (at the root of DGtal) ?

**Comment by dcoeurjo** [comment]
+ new line in the `AUTHORS` file :)

**Comment by dcoeurjo** [comment]
👌🎉

**Comment by dcoeurjo** [comment]
thanks @jdelanoy ! Merging.

**Pull request merged**
