### PR TITLE
Par dir collapse

### PR DESCRIPTION
**Pull request by copyme**
Implementation of a parallel directional collapse thinning in cubical complexes. The code was written under my supervision by M1 students from an international program provided by ESIEE Paris: @bmart36, @midomellouli and @MOH91.

*TODO*
- [x] documentation

In the future, the result could be improved if some one---probably the next year students---could implement lambda-medial axis.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Thanks for the PR. Few remarks:
* this PR won't be part of 0.9.1that should be released this week (documentation missing...)
* it is a great idea to have student projets adding features to DGtal. However, I would recommend that the students appear in the git commit history keep track of their contributions (ask them to clone and to commit on one of your branch for instance). I saw that their names appear in the file headers, which is good, but please also add them to the authors list.

**Comment by copyme** [comment]
@dcoeurjo 

1. That is a sure thing and no problem.
2. I tried to motivate them to use git but at some point they just stopped to use it -- they were not familiar with it before and had some difficulties. Nevertheless, they are going to write documentation (there are extra points to get from the course) and for that I will try to motivate them again. We will see. Thanks for remaining me about authors' list. I forgot about it.

**Comment by dcoeurjo** [comment]
great :) thanks.

**Comment by dcoeurjo** [comment]
(Waiting for PR #1086 and we'd be ready to release :sunglasses: )

**Comment by copyme** [comment]
Hello! I will finish this PR around 6~7 July. Sorry for a delay but schedule is tight.

**Comment by copyme** [comment]
I've added some documentation. It seems that the errors on travis are not related to my code.

**Comment by copyme** [comment]
Well, my bibtex editor removed some entries...

**Comment by copyme** [comment]
@dcoeurjo I think it is ready for review. Are there any new requirements, in general? I do remember some discussion about this.

**Comment by rolanddenis** [comment]
On my side, Github shows, on this page, all DGtal commits since this PR is open (724 modified files) ... don't you ?

I did the test and it seems that if you recreate the PR, the diff is then properly displayed.

**Pull request closed without merging**
