### PR TITLE
Fix testLongvol and testCompressedVolWriter

### PR DESCRIPTION
**Pull request by rolanddenis**
# PR Description

Fix `testLongvol` and `testCompressedVolWriter` that was failing on some configurations.

Actually, it was due to a left-shift overflow (eg a 56 bits left-shift of a `char`) in the `read_word` method of `LongvolReader` and it was possible to make tests failing on more configurations by making tested value larger (see first commit).

# Checklist

- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Nice, what about testCompressedVol ? Have you been able to reproduce the bug?

**Review by dcoeurjo — APPROVED** [review]
All good to me.. thanks !

**Comment by rolanddenis** [comment]
> Nice, what about testCompressedVol ? Have you been able to reproduce the bug?

You mean `testCompressedVolWriter`? I don't find any `testCompressedVol` :thinking: 

BTW, the last CI fails because of an assertion on the computational time in `testPolygonalCalculus` that should be lower with cache enabled compared to without cache.

**Comment by dcoeurjo** [comment]
> You mean `testCompressedVolWriter`? I don't find any `testCompressedVol` 🤔

my bad.. I removed my comment ;)

> BTW, the last CI fails because of an assertion on the computational time in `testPolygonalCalculus` that should be lower with cache enabled compared to without cache.

Let me check. thx anyway

**Pull request merged**
