### PR TITLE
Fixing deprecated throw exception specifications and indentation warnings

### PR DESCRIPTION
**Pull request by rolanddenis**
# PR Description
- Fixing deprecated throw exception specifications and replacing `throw()` by `noexcept`
- Fixing indentation warnings with g++ 7.x

# Checklist

- ~~[ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).~~
- ~~[ ] Doxygen documentation of the code completed (classes, methods, types, members...)~~
- ~~[ ] Documentation module page added or updated.~~
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
I am a bit confused... Does the fix consist in removing all exceptions ? 

Maybe I  haven't understood properly the ```noexcept```. I have the feeling that we are loosing something here (e.g. the type of the exceptions that was explicit before).

**Comment by rolanddenis** [comment]
Specifying which exception a function may throw has been deprecated in C++11 for many reasons (see https://stackoverflow.com/questions/13841559/deprecated-throw-list-in-c11 and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html ). I agree that we loose the knowledge of what exception we may have to catch but it seems to be very hard to guarantee in a generic code ...

Instead of that, we can specify that a function doesn't throw any exception with `noexcept` or `noexcept(true)` (see http://en.cppreference.com/w/cpp/language/noexcept_spec ), or that her exception specification depends on the result of an expression ( `noexcept( expression )` ) or on other function exception specification using the `noexcept` operator ( see http://en.cppreference.com/w/cpp/language/noexcept ) , e.g `noexcept(noexcept(otherfunction()))`.

If a function has the  `noexcept(true)` specifier, no exception handler is generated (maybe a performance gain ???) and if it still throws an exception, it result in the program termination.

**Comment by phcerdan** [comment]
Answering here from #1284:
tested with default configuration (examples ON), and no warnings! :+1:

**Comment by dcoeurjo** [comment]
thanks @rolanddenis for the feedbacks..

**Comment by rolanddenis** [comment]
We can additionally document the exceptions with the `@throw` doxygen command ?

**Comment by dcoeurjo** [comment]
Ok travis is fine now. Shouldn't we remove the ```DGtal::IOException``` and update the doc accordingly ?

**Comment by rolanddenis** [comment]
What do you mean ? Removing all the exceptions ?

**Comment by dcoeurjo** [comment]
nevermind;) my remark was odd
Merging this dude..
thx

**Pull request merged**
