### PR TITLE
Adding Nicolas Aubry to Authors list

### PR DESCRIPTION
**Pull request by dcoeurjo**
ping @naubry, @kerautret

### CODE REVIEW

**Comment by JacquesOlivierLachaud** [comment]
Nicolas Normand is missing too, isn't he ?
The same holds for Roland Denis.

**Comment by kerautret** [comment]
we miss the change log also if i am not wrong ;)

**Comment by dcoeurjo** [comment]
You're right.. I was too excited to merge it. I'll do it

**Comment by dcoeurjo** [comment]
Changlog updated.
merging

**Pull request merged**
