### PR TITLE
Compressed Vol format

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

This PR adds a new Version (3) to Vol file format allowing to have compressed volumetric data using zlib.  In Version 2, vol consists in an ASCII header and then the raw data in binary mode. This new version compresses the raw data using zlib/boost-filter, saving  huge storage.

VolReader and VolWriter have been updated and can still import/export Version 2 vols. 

To be able to perform such compression, zlib must be installed in the system (and is thus a new mandatory dependency in DGtal). This lib is highly standard and shouldn't be a problem. I could have make this dependency optional but if you all agree, I would like this "compressed" version to be the default one.

I've planned a ```upgradeVol``` tool to upgrade a vol file from Version 2 to 3 in ```DGtalTools```.

Additionaly, the Boost lib filter I use needs boost>1.50.

🎄 🎁 🎄 

## TODO
 - [x] update LongvolReader/LongvolWriter accordingly
 - [x] Check DGtalConfig.cmake.in

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
this PR depends on #1227

**Comment by dcoeurjo** [comment]
@kerautret I think I would need your help to download and install zlib DLLs on appeveyor windows script.

The DLL is available here: http://www.winimage.com/zLibDll/ but I don't know of to deal with the appeveyor script.
thx

**Comment by kerautret** [comment]
Nice features ! Yes I will look it !

**Comment by phcerdan** [comment]
Tested with current LookUpTables -NeighborhoodConfigurations- and `zlib` solution works really well. The compressed tables are `4.0 kb`, and using `boost::iostream` they read fast. Really clean approach, way better than decompressing at `CMake` time, saving space to users.

+1 on adding `zlib` dependency

**Comment by copyme** [comment]
Same here +1 for zlib.

**Comment by dcoeurjo** [comment]
I've exchanged with @jacquesolivierlachaud about this PR and the new zlib dep is also fine for him. @kerautret, have you tried the windows build through Appeveyor ? Thx

**Comment by dcoeurjo** [comment]
FYI: here you have a simple command line tool to convert compressed vol to raw https://github.com/dcoeurjo/VolGallery/blob/master/tools/vol2raw.sh

(yup, the compressed part can be decompressed using gzip with the appropriate header 😄 )

**Comment by dcoeurjo** [comment]
The appveyor script is now ok (thanks @kerautret ). The DGtalTools target is still failing on travis but a DGtaltools pending PR has a fix.

Can someone have a look to the code so that I can merge this PR ? thx

**Comment by kerautret** [comment]
yes I look it for the DGtalTools ;)

**Comment by kerautret** [comment]
I reloaded Travis from the DGtools merged ;)

**Comment by kerautret** [comment]
@dcoeurjo sorry I have included the master in the PR on your branch ;(

**Comment by dcoeurjo** [comment]
Okay.. bots look fine. Merging this dude.
thanks everyone for your help

**Pull request merged**
