### PR TITLE
Travis container

### PR DESCRIPTION
**Pull request by dcoeurjo**
Experimenting Travis's new bot system with Docker containers. Should lead to x2 faster builds.

(At this point, I had to desactivate qglviewer tests, working on it with travis.)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
(please keep this PR open while I'm fixing the travis)

**Comment by dcoeurjo** [comment]
ITK pending whitelist: https://github.com/travis-ci/travis-ci/issues/4415

**Comment by dcoeurjo** [comment]
libqglviewer: https://github.com/travis-ci/travis-ci/issues/4414

**Comment by dcoeurjo** [comment]
graphicsmagick: https://github.com/travis-ci/travis-ci/issues/4364

**Comment by dcoeurjo** [comment]
The travis script is working, Travis CI bots now start instantly and the total build duration has been divided by 2.

**Comment by dcoeurjo** [comment]
Doing self merge

**Comment by zmughal** [comment]
Just FYI, `libinsighttoolkit3-dev` is now available to Travis-CI containers.

**Comment by dcoeurjo** [comment]
thx a lot @zmughal, I'll update my scripts.

**Pull request merged**
