### PR TITLE
Add extra exceptions for arithmetic and types operations

### PR DESCRIPTION
**Pull request by copyme**
This PR allows for extra exceptions in the debug mode (G++).

So, without these few lines we have all the test passing:

> 100% tests passed, 0 tests failed out of 193
> 
> Total Test time (real) = 448.64 sec
> 

But if we run the tests with the additional exceptions we get:

> 99% tests passed, 2 tests failed out of 193
> 
> Total Test time (real) = 451.77 sec
> 
> The following tests FAILED:
>          54 - testMultiStatistics (Failed)
>          86 - testLambdaMST3D (NUMERICAL)
> Errors while running CTest

The bugs related to LambdaMST3D are already fixed in #1339

It is not that bad only two tests failed (and one of mine). We can think about adding different types of extra exceptions but allowing all may cause problems with boost, for example.

### CODE REVIEW

**Comment by copyme** [comment]
First it looks like there is another flaoting-point error see:

/home/travis/build/DGtal-team/DGtal/tests/dec/testHeatLaplace.cpp:125: FAILED:
due to a fatal error condition:
  SIGFPE - Floating point error signal

Second the thing does not work on OS X. I will have to turn it on only for Linux.

**Comment by dcoeurjo** [comment]
Can you see the issue with `testMultiStatistics`? I don't know of to trace back the bug..

**Comment by copyme** [comment]
@dcoeurjo OK, I will try to find a solution once I will have a bit of time.

**Comment by dcoeurjo** [comment]
Thx.. Not easy to locate the actual bug with the SIGFPE signal which does not provide a lot of information

**Comment by copyme** [comment]
@dcoeurjo Yup, I use GDB to stop at the signal and try to understand where is the problem. I think there are better techniques to deal with this. I will need to have a look at.

**Comment by dcoeurjo** [comment]
I see.. thx anyway..

**Comment by dcoeurjo** [comment]
can you please merge with the master ? Are all tests passing now ?

**Comment by copyme** [comment]
@dcoeurjo They should, lets see what travis will tell us right now.

**Comment by copyme** [comment]
@dcoeurjo One test is still failing. The fix is in a non-merged branch: Curves3D. I am working on it.

**Comment by dcoeurjo** [comment]
If #1339 is merged, will the remaining test be fine?

**Comment by dcoeurjo** [comment]
ping @copyme

**Comment by copyme** [comment]
@copyme it should be fine I will merge master and we will see

**Comment by copyme** [comment]
@dcoeurjo sorry for the delay, I have not seen your message. I just added a changelog entry, and if the tests go then you can merge, I think.

**Comment by copyme** [comment]
@dcoeurjo, in fact, there are bugs in the tests. The fix discovered new issues. I will have a look at and try to fix them.

**Comment by dcoeurjo** [comment]
👌

**Comment by copyme** [comment]
@dcoeurjo I will need a hand to fix these issues.

So, in `testHeatLaplace.cpp` the problem is here:

` 
const double cut_locus = log( - log1p( t ) ) + 2.;
`
the value of ` - log1p( t )` is `-0.0953102` but `std::log` does not accept negative values:

> If the argument is negative, NaN is returned and FE_INVALID is raised. 

Since I do not understand the code well (and I have no time to) I need a piece of precise information on how to fix this issue.

**Comment by copyme** [comment]
ping @cgurps

**Comment by cgurps** [comment]
You can replace this line by

`const double cut_locus = 3.0;`

The value doesn't really mater for this test

**Comment by copyme** [comment]
@cgurps thanks, fixed. @dcoeurjo before merging please review my fix to the bug in `SphericalHoughNormalVectorEstimator`

**Comment by copyme** [comment]
Also, on my machine I get this:

/home/kacper/Projects/DGtal/cmake-build-debug/tests/dec/testLinearStructure
New Block [testing 3d operators]
  [dec | primal 0-cells <-> dual 3-cells (2) | primal 1-cells <-> dual 2-cells (5) | primal 2-cells <-> dual 1-cells (4) | primal 3-cells <-> dual 0-cells (1)]
  New Block [base operators]
    d0
[primal 0-form => primal 1-form (2 => 5)]
-1  1
 0  1
 0  1
-1  0
-1  0
    d2p
[dual 2-form => dual 3-form (5 => 2)]
-1  0  0 -1 -1
 1  1  1  0  0
    [ERR] Fatal Error - assertion (Eigen::MatrixXd(d0.myContainer) == d0_th) failed in void test_manual_operators_3d(): /home/kacper/Projects/DGtal/tests/dec/testLinearStructure.cpp(391)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

But maybe this is Eigen version related?

**Comment by rolanddenis** [comment]
It is related to recent Boost versions (see https://github.com/DGtal-team/DGtal/issues/1268).

**Comment by copyme** [comment]
@rolanddenis thanks for the info!

**Comment by copyme** [comment]
@dcoeurjo I am done here. Just pay attention to the changes mentioned above while merging.

**Comment by dcoeurjo** [comment]
all good.. thanks.

**Pull request merged**
