### PR TITLE
Enabling Eigen in travis

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Update of the travis scripts to enable Eigen tests. This would enables unit-test for the DEC package for instance.

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
I tried it also in my branch but eigen requested on version 3.2 if it has not changed, so I have add a manual install of eigen I PR on it if you want ;)

**Comment by dcoeurjo** [comment]
Let's see the travis outputs 😃 
Travis (with deadsnake ppa) seems to have a eigen 3.3

**Comment by kerautret** [comment]
ok nice in this case ;)

**Comment by dcoeurjo** [comment]
allright. I was wrong. Can you PR your script?

**Comment by kerautret** [comment]
Yes I just have to solve the conflict ;)

**Comment by kerautret** [comment]
@dcoeurjo done, for info I switch the Eigen opt in the config with no warning error since eigen produce a lot of warning ;)

**Comment by dcoeurjo** [comment]
Ok.. issues spotted.. Inviting @elcerdo to join this thread

**Comment by elcerdo** [comment]
Every tests (except testClone2 with gcc) pass on my machine with gcc and clang in debug and release modes. Logs are coherent with what is expected. However logs for the clang travis build of testLinearStructure are incoherent with what i observe on my machine and should rightfully fail.

What kind of black magic is this? Any idea of what is happening?

**Comment by elcerdo** [comment]
The problem boils down to the fact that boost hashes are different in travis (version 1.46.1) and on my computer (version 1.60.0). i will try disabling all tests versus hardcoded values to test this hypothesis.

**Comment by dcoeurjo** [comment]
@kerautret, can you please have look to the Eigen discovery in cmake ?

**Comment by elcerdo** [comment]
Now travis doesn't find eigen anymore.
Any idea on how to fix this?

**Comment by kerautret** [comment]
Perhaps upper case since the test is "EIGEN3_FOUND" I pushed direct to your branch...

**Comment by kerautret** [comment]
I apply plenty of test but even with 3.3 it is not detected by cmake...
I tried to make install or direction link to include, same result with pkg... I give up for now... perhaps we could include the header in inside DGtal src ?

**Comment by kerautret** [comment]
at best I have that:
capture d ecran 2016-11-13 a 01 51 03

**Comment by kerautret** [comment]
awful the debug in travis but with the last commit now Eigen 3.3 is fine and detected in Cmake:
capture d ecran 2016-11-13 a 10 41 42

It always fails, what should be done now is:
 - [ ] Remove warning display of gcc  ( it fails for now : too numerous due to eigen and the memory if full over 4Mo of log)
 - [ ] Fix the error related to testLinearStructure

**Comment by dcoeurjo** [comment]
Please hold on a bit. I would like to refactor the Travis (scripts instead of if then) and with the new Trusty (maybe no need to manually install deps, https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/)

**Comment by kerautret** [comment]
ok (and a little busy for now and next week) but yes perhaps the new version of eigen will be available ;)

**Comment by dcoeurjo** [comment]
No problem. I'm on it

**Comment by dcoeurjo** [comment]
@kerautret , @elcerdo I have refactorized travis script (with child scripts in .travis/ folder). It is clearer now and the Eigen install seems to be ok now (version 3.2.10).

@elcerdo can you please have a look to the DEC issues with this eigen ?

On mac, there is an issue with libqglviewer but it is not related to Eigen issues.

**Comment by dcoeurjo** [comment]
ping @elcerdo

**Comment by elcerdo** [comment]
DEC tests seams to be fixed. Remaining Travis failures are caused by compilation/cmake errors.
FYI tests failed because there has been a change in boost::hash_range between the antiquated Travis boost version and reasonably recent desktop boost version.

**Comment by dcoeurjo** [comment]
Ok. Travis is fine again.

**Comment by dcoeurjo** [comment]
mreging

**Pull request merged**
