### PR TITLE
Fixing cmake config file install

### PR DESCRIPTION
**Pull request by dcoeurjo**
Fixing #1095

### CODE REVIEW

**Comment by kerautret** [comment]
I just checked the PR but for the install copy always the file here:
 /usr/local/share/DGtalConfig.cmake

**Comment by dcoeurjo** [comment]
are you sure to have removed your cmake cache ?

**Comment by kerautret** [comment]
oops you are right:
/usr/local/lib/DGtal/DGtalConfig.cmake
so looks fine if I am not wrong (since we don't suppose  cmake > 2.6.3 )

**Comment by dcoeurjo** [comment]
I don't understand what you mean with cmake>2.6.3?

**Comment by kerautret** [comment]
as @phcerdan mention, CMake 2.6.3 and above looks in /lib/cmake/Foo/ but I have checked in the CMakeLists.txt we have cmake_minimum_required (VERSION 2.6) so it can keep it ;)

**Comment by dcoeurjo** [comment]
Got it, thanks.

**Comment by kerautret** [comment]
ok merging all get fines also with DGTalTools from user or travis install :)

**Pull request merged**
