### PR TITLE
Fix deprecated warning about location of boost header.

### LINKED ISSUE #1327: Deprecated location of boost header: common_factor_rt.hpp
boost version: 1.67.0-4

```
In file included from /DGtal/DGtal-src/src/DGtal/geometry/curves/ArithmeticalDSSComputer.ih:35,
                 from /home/phc/Software/DGtal/DGtal-src/src/DGtal/geometry/curves/ArithmeticalDSSComputer.h:567,
                 from /DGtal/DGtal-src/src/DGtal/io/Display2DFactory.h:52,
                 from /DGtal/DGtal-src/src/DGtal/io/boards/Board2D.h:428,
                 from /DGtal/DGtal-src/examples/geometry/volumes/distance/voronoimap2D.cpp:52:

/usr/include/boost/math/common_factor_rt.hpp:13:63: note: #pragma message: This header is deprecated. Use <boost/integer/common_factor_rt.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/integer/common_factor_rt.hpp>"
```

### PR DESCRIPTION
**Pull request by phcerdan**
Triggered when using boost 1.67.0-4

header name: common_factor_rt.hpp
moved from <boost/math/common_factor_rt.hpp>
to <boost/integer/common_factor_rt.hpp>

Fix #1327

- [NA] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [NA] Doxygen documentation of the code completed (classes, methods, types, members...)
- [NA] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [NA] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [NA] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
thanks @phcerdan !

Do we need to bump up the min version of boost (cmake, doc,...) ?  
(Currently, we ask for boost>= 1.50).

**Comment by phcerdan** [comment]
Umm, yeah, the file was moved in the new location in version 1.58... a significant jump from current required version: 1.50.

**Comment by phcerdan** [comment]
Pumping the boost version for just a warning might be an overkill, this can be fixed whenever you want to pump boost version for other reasons, or when the deprecation warning becomes an error in future releases of `boost` (I don't think that will happen soon).

**Comment by dcoeurjo** [comment]
Agree....

**Pull request closed without merging**
