### PR TITLE
[WIP] Issue doc deploy

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Checking the doc deploy in travis

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by rolanddenis** [comment]
In `.travis.yml`, I have added the `strategy`directive in the `deploy` section of the documentation. I have set it to `git` because Travis told me (info message in continuous integration) that it is the default value. Maybe `api` is the right value? (See https://docs.travis-ci.com/user/deployment-v2/providers/pages/#shared-options)

**Comment by dcoeurjo** [comment]
I've no idea... Let me merge this PR to see if the doc is correctly deployed

**Comment by rolanddenis** [comment]
Still failing: https://travis-ci.org/github/DGtal-team/DGtal/jobs/663390671?utm_medium=notification&utm_source=github_status

**Comment by dcoeurjo** [comment]
yep

**Pull request merged**
