### PR TITLE
Fix loadTable in Windows

### PR DESCRIPTION
**Pull request by phcerdan**
Add `std::io::binary` flag to `ifstream`

In Linux the missing flag wasn't a problem:
https://stackoverflow.com/questions/60915861/decompression-with-boost-zlib-crashes-on-windows

Reported: https://github.com/phcerdan/SGEXT/issues/48

# Checklist

- [NA] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [NA] Doxygen documentation of the code completed (classes, methods, types, members...)
- [NA] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by phcerdan** [comment]
I think the failing travis is a false positive. Could you please re-trigger it @dcoeurjo?

**Comment by dcoeurjo** [comment]
I wasn't able to retrigger the build so I minor edit the Changelog.

**Review by dcoeurjo — APPROVED** [review]
There are still some travis weird issues but I approve this PR. Thanks @phcerdan

**Comment by phcerdan** [comment]
Green travis! :sparkles:

**Review by dcoeurjo — APPROVED** [review]

**Pull request merged**
