### PR TITLE
Cmake flags and cpp11

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Following #1283 , fix the way we set the c++11 flags in cmake.

# Checklist

- ~~[ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).~~
- ~~[ ] Doxygen documentation of the code completed (classes, methods, types, members...)~~
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by phcerdan** [comment]
There are hard-coded flags in [DGtalConfig.cmake.in](https://github.com/DGtal-team/DGtal/blob/master/cmake/DGtalConfig.cmake.in) too.

I think we can remove CPPcheck11 completely (I sent you a PR for your branch doing this).

**Comment by dcoeurjo** [comment]
thanks for the PR @phcerdan. I agree that CPP11CHECK is a bit overkill now but at least it would warn the user that is compiler is not C++11 compliant before trying to build. Maybe we could just keep one simple ```try_compile``` for that. 

What do you think ?

**Comment by dcoeurjo** [comment]
(thx for ```DGtalConfig.cmake.in```, fixed)

**Comment by dcoeurjo** [comment]
@kerautret could you please propagate this to DGtalTools and DGtalTools-contrib ?

**Comment by kerautret** [comment]
@dcoeurjo yes I look it!

**Comment by kerautret** [comment]
done (but just cmake version check since as discussed the check is done first by DGtal)

**Comment by phcerdan** [comment]
@dcoeurjo sounds good to me!

**Comment by phcerdan** [comment]
We should test this option:
`set(CMAKE_CXX_EXTENSIONS OFF) #...without compiler extensions like gnu++11`

I have faced problems in `boost` without the `-std=gnu++11` flag (just using `-std=c++11`):

One of many errors triggered from boost:
```
/home/phc/repository_local/SGEXT/build-superbuild/dep-install/include/boost/math/special_functions/detail/igamma_large.hpp:501:7: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
/home/phc/repository_local/SGEXT/build-superbuild/dep-install/include/boost/math/special_functions/detail/igamma_large.hpp:502:7: error: unable to find numeric literal operator ‘operator""Q’
       BOOST_MATH_BIG_CONSTANT(T, 113, 0.243619480206674162436940696707789943e-10),
```

I did a workaround about this after reading about the same issue in [CGAL](https://github.com/CGAL/cgal/issues/1685) by using `-std=gnu++14` with `gcc`. But using `gnu++11` should suffice.

**Comment by dcoeurjo** [comment]
@phcerdan ok but we don't to manually set the flags as suggested in CGAL fix.
Should I juste remove the line with the "OFF" to extensions ?

**Comment by phcerdan** [comment]
@dcoeurjo I think so, the `OFF` in the extensions should suffice. I guess cmake then uses `gnu++11`  instead of `c++11` when using `gcc`.

**Comment by dcoeurjo** [comment]
👌

**Comment by dcoeurjo** [comment]
Merging

**Pull request merged**
