### PR TITLE
Fix memory issue of 3DImageViewer when slicing image and display SDP

### PR DESCRIPTION
**Pull request by kerautret**
Thanks from @akrah bug datected, now it should be fine ;) !
Can you confirm @akrah ?

### CODE REVIEW

**Comment by akrah** [comment]
Yes, I confirm: this works well now (even if Travis says no) !
Thanks @kerautret !

**Comment by kerautret** [comment]
great thanks!

**Comment by dcoeurjo** [comment]
ok fine. @kerautret could you please fix the doxygen issue on Mesh classes ? (cf travis log)

**Comment by kerautret** [comment]
ok I look it

**Comment by kerautret** [comment]
@dcoeurjo done

**Comment by dcoeurjo** [comment]
ok better. thanks. merging

**Pull request merged**
