### PR TITLE
Create a new sample sdp

### PR DESCRIPTION
**Pull request by ngophuc**
A sample sdp file of contourS.fc generated from freeman2sdp

# PR Description

*your description here*

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Is this new sample used in an example or a test file ?

**Comment by dcoeurjo** [comment]
But the digitizer is in the DGalTools right ?

**Comment by ngophuc** [comment]
> But the digitizer is in the DGalTools right ?

yes (for now)

**Comment by dcoeurjo** [comment]
If the polyline is not used in any test/example, I would prefer not to include it in DGtal (you can add it in DGtaltools if you want).
We are trying to limit the size of the repo.

**Comment by ngophuc** [comment]
Ok, I see. I will add it in DGtaltools then.

**Comment by dcoeurjo** [comment]
Thx

**Pull request closed without merging**
