### PR TITLE
Integral Invariant Tangent Estimator error in 2D

### PR DESCRIPTION
**Pull request by cgurps**
# PR Description

Fixed an error for II tangent estimator on 1D curves (missing init() function in the functor)

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
hi @cgurps, Can you please check the build bots ?

**Comment by cgurps** [comment]
I got this error

g++-5: internal compiler error: Killed (program cc1plus)

which I think is travis related

**Comment by rolanddenis** [comment]
Yes, it is travis related, maybe due to a high memory usage ... Sometimes it passes when triggering Travis's job again. Nevertheless, there is the recent PR #1335 that has change the Travis script with maybe less compilation problems ... could you try it by merging the master branch into this PR ?

**Comment by dcoeurjo** [comment]
@cgurps can you please update this branch with the master and add a changelog entry ?

**Comment by dcoeurjo** [comment]
@rolanddenis the @ref produces issues with the doc (apparently, the problem occurs when the filename/key starts with a number.. )

**Comment by dcoeurjo** [comment]
Ok fine.. pending doc issue has been fixed in the master. Merging. thanks

**Comment by rolanddenis** [comment]
Nope, actually its seems to be a bug with doxygen when references start with a digit, and that is the case since PR #1331 . I'm on it !

**Comment by dcoeurjo** [comment]
yep I reverted my edits on the master

**Pull request merged**
