### PR TITLE
Upgrading to Catch 2.9

### PR DESCRIPTION
**Pull request by rolanddenis**
# PR Description

One more upgrade of Catch to be able to return a value during the benchmarks so that to avoid dead code elimination by the compiler in release mode.

# Checklist

- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
;) 2.9 released 10 hours ago.. 

(Now I understand the return issue while  following the doc)

**Comment by rolanddenis** [comment]
We are up to date :laughing:

**Comment by rolanddenis** [comment]
Done :+1:

**Comment by dcoeurjo** [comment]
all good thanks

**Pull request merged**
