### PR TITLE
Fix bug of 3dCurvatureViewer and 3dCurvatureViewerNoise

### PR DESCRIPTION
**Pull request by kerautret**
The bounds were never good in the scanner (lower dim).
Perhaps @JacquesOlivierLachaud  can confirm since I back port it from ImaGene ;)

### CODE REVIEW

**Comment by kerautret** [comment]
It works with @akrah computer, perhaps just wait the Markus test ;)

**Comment by JacquesOlivierLachaud** [comment]
Does the fix hide another bug in KSpace::lowerBound and upperBound ?

**Comment by kerautret** [comment]
Yes perhaps since I changed the KSpace::lowerBound  into KSpace::lowerCell but it could be also the KSpace::uNext( p, dir_low_uid, dir_up_uid ) which continue when cell of lower dim are given ?

**Comment by dcoeurjo** [comment]
Thanks, merging

**Pull request merged**
