### PR TITLE
add color in MeshWriter to export obj file

### PR DESCRIPTION
**Pull request by kerautret**
Small edits to have color when exporting mesh in OBJ format (was already done in OFF but not in OBJ)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
For Obj export of meshes,  is   ```board3D<< aMesh; board3D.saveOBJ()``` equivalent to exportObJ ?
I don't know if we need to duplicate the code for similar feature.

**Comment by kerautret** [comment]
perhaps quite similar, but for me I am not sure that a first user will have the reflex to use Board just to export a mesh object ? As you want but for me it is more logic if Board call MeshWriter to export than the inverse. But I can call the board writer

**Comment by kerautret** [comment]
... in the current export2OBJ_colors functions...

**Comment by dcoeurjo** [comment]
The export code in Board is also shared by Viewer3d. 
The difference I see is could be that board exports the mesh as a set of triangles whereas your code exports it as a triangular surface.. 
Could you please confirm me ?

**Comment by kerautret** [comment]
Yes I confirm, it takes all the faces which are not necessary a triangles.

**Comment by dcoeurjo** [comment]
Actually board can also export polygonal faces but I meant that for triangular meshes, vertices are duplicated in board which may not be the case in your export. Do you agree ?

**Comment by kerautret** [comment]
Ha ok, yes vertices are only given once with also materials with colors.

**Comment by dcoeurjo** [comment]
@kerautret the testColor.obj does not show up colors on meshlab. have you used something specific ? Please check for instance material syntax we use in Board3D

**Comment by kerautret** [comment]
I think that it MeshLab which by default apply a color rendering by vertex, but here it is by face ;)
I don't know why it does't check it by default, but if you check the option in render menu -> Color -> Per Face it should be fine in theory...

**Comment by dcoeurjo** [comment]
Maybe be I'm wrong but after checking the wikipedia description of OBJ, per-vertex-color seems to be more standard than face color

**Comment by kerautret** [comment]
ok, however since it is given for mesh as face color it is logic to do it.
We can export it perhaps later when Mesh will have color on vertex?

**Comment by dcoeurjo** [comment]
as you whish

**Comment by kerautret** [comment]
ok for me for merging and I will add an issue dealing with color on vertex with obj export

**Comment by dcoeurjo** [comment]
done

**Comment by dcoeurjo** [comment]
thanks

**Pull request merged**
