### PR TITLE
Travis -> Github Actions

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

TODO:
- [x] Build with deps
- [x] DGtalTools
- [x] Doc
- [x] Deploy
- [x] Add Qt / qglviewer

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
Nice! I try to do it for the tools ! and will review in the same time ;)

**Comment by dcoeurjo** [comment]
All done for this one.

**Comment by dcoeurjo** [comment]
Can someone have a look to this PR ? It is blocking several pending PR that are messing up with travis..

**Review by kerautret — APPROVED** [review]
Looks fine, and can be merged at least to have a check in live. I try to apply the same on DGtalTools. Just perhaps the changelog ?

**Comment by dcoeurjo** [comment]
oops I forgot the Changeling, thx

**Pull request merged**
