### PR TITLE
Doc update in DEC

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

minor doc update (package description page)

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
you can just have a look to https://github.com/DGtal-team/DGtal/pull/1734/files#diff-3b9c52f1c01fb9619caa008aeed11cd7af8ee9b98516e0eb8dbcea2f0bba6408 (packageDEC.dox)

**Comment by JacquesOlivierLachaud** [comment]
All good. Merging.

**Comment by JacquesOlivierLachaud** [comment]
Do you know what is the problem with the windows built ?
 It is not launched.

**Comment by dcoeurjo** [comment]
Not really...

**Pull request merged**
