### PR TITLE
Fix bug in VoxelComplex when cell is at boundary of kspace.

### PR DESCRIPTION
**Pull request by phcerdan**
Using KSpace::PreCell in VoxelComplex mask methods.
Add an override to `belongs` method to work with precells.
This belongs returns false if cell is not valid in current kspace
instead of an error.

Adds internal const correctness to various methods.

Also corrects minor style issues.

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [NA] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by phcerdan** [comment]
This change is cherry-picked from #1448

**Comment by phcerdan** [comment]
Rebased on top of master. Let me know if I can help to move this forward.

**Comment by dcoeurjo** [comment]
thanks @phcerdan

**Comment by dcoeurjo** [comment]
all good.. merging.

**Pull request merged**
