### PR TITLE
Travis modification to show output on failed tests.

### PR DESCRIPTION
**Pull request by phcerdan**
Pass argument from make test to ctest:
make test ARGS=--output-on-failure
Showing verbose output on failed tests.

### CODE REVIEW

**Comment by phcerdan** [comment]
It works in all Travis configurations, it shows verbose output only in failing tests.
I will revert the introduced test failure and squash the extra commits after your review.

**Comment by dcoeurjo** [comment]
Excellent !! I didn't know this make test option. Can you please revert the bug commit ?

Thanks a lot

**Comment by phcerdan** [comment]
Done! The option came from [ctest](https://cmake.org/cmake/help/v3.0/manual/ctest.1.html).

**Comment by dcoeurjo** [comment]
Great;) Many thanks.

**Pull request merged**
