### PR TITLE
Fix the CSS file for Doxygen

### PR DESCRIPTION
**Pull request by jlevallois**
# PR Description

Hello everyone!
Happy new year! 🎄🎁 ☃️ 🎉  

This small PR will fix an issue with the CSS file for the documentation due to a Doxygen version upgrade.
Also, I've removed some CSS files we don't use anymore.

Before:
image

After:
image

I've tested it on macOS, with Safari, Chrome and Firefox.

:octocat:  

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
wop wop wop

**Comment by dcoeurjo** [comment]
THx! could you please add a new changelog entry ?

**Comment by jlevallois** [comment]
Done :)

**Review by dcoeurjo — APPROVED** [review]
🚀 🦈

**Pull request merged**
