### PR TITLE
[WIP] Fixing Travis build

### PR DESCRIPTION
**Pull request by rolanddenis**
# PR Description

Fixing Travis conflict between `matrix` and `jobs` directives, and some other warnings and infos (see #1463)

We should maybe wait a little bit before merging in case of deployment of Travis dpl v2 was a mistake...

# Checklist

- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
waoh.. thx for the debug....  looks like you've spotted the bug. 
How did you find it?

**Comment by dcoeurjo** [comment]
👌 merging this one BTW (fixes Bertrand's mail)

**Comment by dcoeurjo** [comment]
oops I merged the wrong duplicate :)

**Comment by dcoeurjo** [comment]
could you just push a Changelog entry ?

**Comment by rolanddenis** [comment]
> waoh.. thx for the debug.... looks like you've spotted the bug.
> How did you find it?

No magic :sweat_smile: : in the job details from your PR : https://travis-ci.org/github/DGtal-team/DGtal/builds/662684925/config?utm_medium=notification&utm_source=github_status

Just below the two tabs `Buid jobs` and `View config`, there is a line `Build config validation` with a red cross meaning that there is an error in the config. Expanding the line, it tolds about a conflict between `matrix` and `jobs`. In the (not completely updated...) documentation of Travis, I understand that `matrix` and `jobs` directives have been merged in the dpl v2 (that is still documented as in beta stage...)

**Comment by dcoeurjo** [comment]
👌 thx

**Pull request merged**
