### PR TITLE
Fixing CGAL 6.0 breaking change.

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

CGAL 6.0 has no `CGAL_USE_FILE` anymore. 

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
@JacquesOlivierLachaud @kerautret, could you please test the build of this PR activating CGAL on your system ?

**Comment by kerautret** [comment]
> @JacquesOlivierLachaud @kerautret, could you please test the build of this PR activating CGAL on your system ?

Thanks I look it, updating CGal from brew in progress...

**Review by kerautret — APPROVED** [review]
Thanks, looks perfect on my Mac, and DGtalTools also checked with CGal based tools well complied.👏🏻

**Comment by dcoeurjo** [comment]
ok thanks, merging

**Pull request merged**
