### PR TITLE
Fix eigen clear() missing method

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
From using DGtal with ITK that use and transmit its own Eigen version it produces already detected clear() missing method. 
As mentionnes in DGtalTools in issue [354](https://github.com/DGtal-team/DGtalTools/issues/354) of DGtalTools.
It fix both compilation issues of DGtal examples with ITK and the volSurfaceRegularization of DGtalTools.
  
# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Touching the concept may be a bit dangerous. Are there classes / codes using a clear() on the linear algebra backends ?

**Comment by kerautret** [comment]
> Touching the concept may be a bit dangerous. Are there classes / codes using a clear() on the linear algebra backends ?

yes, mainly in dec with k-forms if I am not wrong. Alternatively perhaps we can extend the type by integrating the  clear() method in order to be conform to CVectorSpace requirements. Trying to avoid ITK transmit its own eigen path should be perhaps not very useful since sooner or later it will produce the same error with newer eigen version.

**Comment by dcoeurjo** [comment]
If it's fine for you, I'll keep this to the release 1.4 or 1.3.1, we need to inspect the sideeffects of that (I suspect cmake tweaks to isolate ITK's Eigen)

**Comment by kerautret** [comment]
yes fine for me, it was just a few edit, I will try the add of clear() alternative perhaps safer but perhaps more on 1.3.1 or 1.4

**Comment by dcoeurjo** [comment]
Actually, I had the same itk issue for #1689 and I also had to fix that (the clear() is not a method of the matrix class anymore apparently).. Thanks for the PR and the bug report, I will close this one to avoid conflicts.

Eigen deps in DGtal is still a bit odd with Eigen behind required by DGTal, and also  installed by polyscope and ITK ..

**Pull request closed without merging**
