### PR TITLE
several bugs fixed

### PR DESCRIPTION
**Pull request by troussil**

### CODE REVIEW

**Comment by kerautret** [comment]
Thanks, that looks good, by the way could you check the example: exampleArithmeticalDSL which apply a set fault for me:
 ./examples/geometry/curves/exampleArithmeticalDSL 
New Block [Example exampleArithmeticalDSL]
  Args:   ./examples/geometry/curves/exampleArithmeticalDSL  
  New Block [Naive DSL]
    [ArithmeticalDSL] (2,5,0,5)
by steps [PointVector] {1, 0} [PointVector] {1, 1}
[ArithmeticalDSL] (-2,-5,-4,5)
by steps [PointVector] {-1, 0} [PointVector] {-1, -1}
  EndBlock [Naive DSL] (7.777 ms)
  New Block [Standard DSL]
    [ArithmeticalDSL] (2,5,0,7)
by steps [PointVector] {1, 0} [PointVector] {0, 1}
[ArithmeticalDSL] (-2,-5,-6,7)
by steps [PointVector] {-1, 0} [PointVector] {0, -1}
  EndBlock [Standard DSL] (6.463 ms)
  New Block [ Arithmetical DSL (0, 1, 0) in octant 0]
  EndBlock [ Arithmetical DSL (0, 1, 0) in octant 0] (3.868 ms)
  New Block [ Arithmetical DSL (5, 8, 0) in octant 0]
  EndBlock [ Arithmetical DSL (5, 8, 0) in octant 0] (14.645 ms)
  New Block [ Arithmetical DSL (1, 1, 0) in octant 1]
  EndBlock [ Arithmetical DSL (1, 1, 0) in octant 1] (22.256 ms)
  New Block [ Arithmetical DSL (8, 5, 0) in octant 1]
  EndBlock [ Arithmetical DSL (8, 5, 0) in octant 1] (15.112 ms)
  New Block [ Arithmetical DSL (1, 0, 0) in octant 2]
  EndBlock [ Arithmetical DSL (1, 0, 0) in octant 2] (3.118 ms)
  New Block [ Arithmetical DSL (8, -5, 0) in octant 2]
  EndBlock [ Arithmetical DSL (8, -5, 0) in octant 2] (13.859 ms)
  New Block [ Arithmetical DSL (1, -1, 0) in octant 3]
  EndBlock [ Arithmetical DSL (1, -1, 0) in octant 3] (25.933 ms)
  New Block [ Arithmetical DSL (5, -8, 0) in octant 3]
  EndBlock [ Arithmetical DSL (5, -8, 0) in octant 3] (15.166 ms)
  New Block [ Arithmetical DSL (0, -1, 0) in octant 4]
  EndBlock [ Arithmetical DSL (0, -1, 0) in octant 4] (2.695 ms)
  New Block [ Arithmetical DSL (-5, -8, 0) in octant 4]
  EndBlock [ Arithmetical DSL (-5, -8, 0) in octant 4] (13.854 ms)
  New Block [ Arithmetical DSL (-1, -1, 0) in octant 5]
  EndBlock [ Arithmetical DSL (-1, -1, 0) in octant 5] (22.692 ms)
  New Block [ Arithmetical DSL (-8, -5, 0) in octant 5]
  EndBlock [ Arithmetical DSL (-8, -5, 0) in octant 5] (15.971 ms)
  New Block [ Arithmetical DSL (-1, 0, 0) in octant 6]
  EndBlock [ Arithmetical DSL (-1, 0, 0) in octant 6] (3.934 ms)
  New Block [ Arithmetical DSL (-8, 5, 0) in octant 6]
  EndBlock [ Arithmetical DSL (-8, 5, 0) in octant 6] (15.154 ms)
  New Block [ Arithmetical DSL (-1, 1, 0) in octant 7]
  EndBlock [ Arithmetical DSL (-1, 1, 0) in octant 7] (23.822 ms)
  New Block [ Arithmetical DSL (-5, 8, 0) in octant 7]
  EndBlock [ Arithmetical DSL (-5, 8, 0) in octant 7] (15.964 ms)
  New Block [ Arithmetical DSL (0, 1, 0) in octant 0]
  EndBlock [ Arithmetical DSL (0, 1, 0) in octant 0] (4.407 ms)
  New Block [ Arithmetical DSL (5, 8, 0) in octant 0]
  EndBlock [ Arithmetical DSL (5, 8, 0) in octant 0] (11.289 ms)
  New Block [ Arithmetical DSL (1, 1, 0) in octant 1]
  EndBlock [ Arithmetical DSL (1, 1, 0) in octant 1] (13.284 ms)
  New Block [ Arithmetical DSL (8, 5, 0) in octant 1]
  EndBlock [ Arithmetical DSL (8, 5, 0) in octant 1] (15.022 ms)
  New Block [ Arithmetical DSL (1, 0, 0) in octant 2]
  EndBlock [ Arithmetical DSL (1, 0, 0) in octant 2] (4.923 ms)
  New Block [ Arithmetical DSL (8, -5, 0) in octant 2]
  EndBlock [ Arithmetical DSL (8, -5, 0) in octant 2] (12.919 ms)
  New Block [ Arithmetical DSL (1, -1, 0) in octant 3]
  EndBlock [ Arithmetical DSL (1, -1, 0) in octant 3] (11.855 ms)
  New Block [ Arithmetical DSL (5, -8, 0) in octant 3]
  EndBlock [ Arithmetical DSL (5, -8, 0) in octant 3] (12.272 ms)
  New Block [ Arithmetical DSL (0, -1, 0) in octant 4]
  EndBlock [ Arithmetical DSL (0, -1, 0) in octant 4] (5.477 ms)
  New Block [ Arithmetical DSL (-5, -8, 0) in octant 4]
Segmentation fault: 11

**Comment by kerautret** [comment]
Apparently not related to current PR 944 I test it

**Comment by kerautret** [comment]
You could profit also to add an example reference like in the doc since it does not appear in the section "examples" , for that you just have to add for instance in  file moduleArithDSSReco.dox something like:
/**
   This example shows the recognition of a simple standard digital
   plane with the Chord algorithm (class
   ChordGenericStandardPlaneComputer ). Green points belong to the naive
   plane. Grey points show farther points that also belong to the
   strip.

@see \ref modulePlaneRecognition_sec26

@verbatim
$ ./examples/io/viewers/viewer3D-7bis-stdplane
@endverbatim

@image html coba-stdplane.png "Piece of standard plane."
@image latex coba-stdplane.png "Piece of standard plane." width=5cm

\example io/viewers/viewer3D-7bis-stdplane.cpp
*/

**Comment by troussil** [comment]
Can you create separate issues ?

2015-02-09 14:48 GMT+01:00 Bertrand Kerautret <notifications@github.com>:

**Comment by kerautret** [comment]
yes that done I merge this one ;)

**Pull request merged**
