### PR TITLE
Bugs in back() and front() functions

### PR DESCRIPTION
**Pull request by ngophuc**
*Thanks a lot for contributing to DGtal, before submitting your PR, please fill up the description and make sure that all checkboxes are checked. Please remove these lines in your PR.*

# PR Description

*your description here*

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

In back(): return myL;  instead of return myF; 
In front(): return myF;  instead of return myL;

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Hi @ngophuc , could you please have a look to travis bot outputs ?It seems that your edits break some unitary test.

**Comment by ngophuc** [comment]
Actually, you can ignore my request since apparently the list structure of points in DSS is not like a vector (means front=first element and back=last element) but more like a LILO structure (meas front=last element and back=first element). I just misunderstood it. 

However, I would like to ask if it is possible to add two more functions: **extendFront(InputPoint &aPoint)** and **extendBack(InputPoint &aPoint)** for extending on the left and right of a segment with respect to a given point in this class **ArithmeticalDSS**?  The actual version has extendFront() and extendBack() with respect to the iterator of DSS. 

Thanks

**Comment by dcoeurjo** [comment]
Could you please create a new issue with your feature request ?

**Comment by dcoeurjo** [comment]
I'm closing this PR.

**Pull request closed without merging**
