### PR TITLE
Fix const attribute that shouldn't be

### PR DESCRIPTION
**Pull request by Lieunoir**
# PR Description

Changes a const string attribute to non const, otherwise it conflicts with struct's `operator=` impl

Somehow only gcc 14 gives an error, neither earlier version nor clang complain?

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Thanks for the PR. Nope this issue does not seem to be raised for other compilers... interesting..

**Comment by dcoeurjo** [comment]
Is that the only bug you get from gcc14?

**Comment by Lieunoir** [comment]
Yup, works fine otherwise

**Comment by dcoeurjo** [comment]
I'm on the issue you have with testPolygonalCalculus. In the meantime, could you please add a new entry to the Changelog + CONTRIBUTORS files ?

**Comment by dcoeurjo** [comment]
Thanks for the PR, merging

**Review by dcoeurjo — APPROVED** [review]

**Pull request merged**
