### PR TITLE
[WIP] SimpleMatrix with initializer_list constructor

### PR DESCRIPTION
**Pull request by nnormand**
This PR adds a constructor for SimpleMatrix with an initializer_list argument. This is work in progress: the cofactors are **NOT** computed and it is unclear if they should or not (`setComponent` doesn't).

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
hi @nnormand , I'm on it. Could you please add a test in testSimpleMatrix ?

**Comment by dcoeurjo** [comment]
I agre.. cofactor must be updated before returning the determinant or "cofactor" methods.

**Comment by dcoeurjo** [comment]
fine. can someone review this PR ?

**Comment by JacquesOlivierLachaud** [comment]
I will try to review it this week. One remark: it would be nice to have a non-invasive editor, so that unrelated files are not modified. Here there are 22 files changed, whereas certainly one or two are concerned.

**Comment by dcoeurjo** [comment]
This PR also contains the new .clang-format rules in a previous PR. My push uses this rules to auto-format the modified file. I don't understand why other files have been processed BTW

**Comment by dcoeurjo** [comment]
you only have to review SimpleMatrix constructor.

**Comment by JacquesOlivierLachaud** [comment]
Ok. No problem. I will try to review it tonight.

**Comment by JacquesOlivierLachaud** [comment]
I only looked at SimpleMatrix.* and testSimpleMatrix.cpp. It is fine with me. My only remark is to add in the initialiser_list constructor the fact that matrices are filled in row by row from top left to top right then again to bottom.

**Comment by dcoeurjo** [comment]
agree

**Comment by dcoeurjo** [comment]
I've updated the doc of the constructor. Fine for you ?

**Comment by JacquesOlivierLachaud** [comment]
It is fine with me. I've restarted the travis job that fails because of excess time.
I merge afterwards.

**Pull request merged**
