### PR TITLE
Fix parentheses warning with Catch (again)

### PR DESCRIPTION
**Pull request by rolanddenis**
Second chance for the PR #1067.

The problem is now with expression like
```
REQUIRE( 1+2 == 3 );
```
that emits warning on adding parentheses around ```1+2```. 

It still allows Catch to expand each side of the comparison in case of assertion failure but it forces us to add extra-parentheses when left term contains `+` or `-`. It's more or less the same as when Catch was using `->` operator (but compilation was failing without the extra-parentheses). 

We can also keep this PR as is and wait for an official fix.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Thanks a lot @rolanddenis, let's consider this solution. 
Can you please add an entry to the changelog?

**Comment by rolanddenis** [comment]
Thus we stay on the exact same PR than previously ?

**Comment by dcoeurjo** [comment]
yep (1+2)==5 is way better than ((1+2)==5)
does it generate warnings on your compilers?

**Comment by dcoeurjo** [comment]
(but prev PR was reverted)

**Comment by rolanddenis** [comment]
no, adding parentheses around `+` and `-` avoids the warnings. But if we accept to add those parentheses, we could also go back to `->*` that is surely less prone to generate warnings (less precedence) and that clearly failed to compile (with a message, see https://github.com/DGtal-team/DGtal/blob/master/tests/catch.hpp#L1867 ) instead of having a warning on some compiler.

**Comment by dcoeurjo** [comment]
Up to you.. you're the specialist;)

**Comment by rolanddenis** [comment]
Hum ok, we stay on this PR and we will see if someone complains :)

**Comment by rolanddenis** [comment]
Done. I have also remove extra parentheses from testSimpleRandomAccessRangeFromPoint.

**Comment by dcoeurjo** [comment]
:cool: :ok_hand:

**Pull request merged**
