### PR TITLE
Save light position

### PR DESCRIPTION
**Pull request by kerautret**
overload of some methods in orde to save light source position when the Viewer3D state is saved.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
great.. thanks. merging.

**Comment by dcoeurjo** [comment]
Just a question: is ```.qglviewer``` always created when the viewer is on ?

**Comment by dcoeurjo** [comment]
I would prefer to have an optional behavior to avoid having bunch of .qglviewer file on my folders..

**Comment by kerautret** [comment]
yes the .qglviewer is always created by default from the QGLviewer. We can probably disable it, and since now we can load/save it from the keyboard it should be ok.

**Comment by dcoeurjo** [comment]
I would prefer to have the file generated only when a save position/light is performed (personally, I never use this feature;))

**Pull request merged**
