### PR TITLE
Safeguard for imagemagick dep

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Error messages when trying to use ImageMagick without activating the dependency in cmake

# Checklist

- ~~~[ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).~~~
- ~~~[x] Doxygen documentation of the code completed (classes, methods, types, members...)~~~
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by rolanddenis** [comment]
I would say since 1.58.0:
- 1.57.0: https://www.boost.org/doc/libs/1_57_0/boost/integer/common_factor_rt.hpp
- 1.58.0: https://www.boost.org/doc/libs/1_58_0/boost/integer/common_factor_rt.hpp
but, according to this documentation page ( https://www.boost.org/doc/libs/1_68_0/libs/math/doc/html/gcd_lcm.html ) and to the corresponding file source ( https://www.boost.org/doc/libs/1_68_0/boost/math/common_factor_rt.hpp ), the old path should still redirect to the new one...

**Comment by dcoeurjo** [comment]
Thx @rolanddenis. I didn’t get the info on boost website

The deprecated path should redirect but not exactly because the build fails on macOS (last boost release).

**Comment by dcoeurjo** [comment]
I’ll add ifdef using boost version.

**Comment by dcoeurjo** [comment]
all good now

**Comment by dcoeurjo** [comment]
agree;)

**Comment by rolanddenis** [comment]
Merging, thanks !

**Pull request merged**
