### PR TITLE
fix light render when change scale

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
Small fix that appears when changing the scale of the viewer:
capture d ecran 2016-11-12 a 12 39 48

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
@kerautret can you please have a look to #1214 ?

**Comment by kerautret** [comment]
yes sorry I miss the comment ;) I have pushed a try..

**Comment by kerautret** [comment]
@dcoeurjo merging ?

**Comment by dcoeurjo** [comment]
all good. thanks.

**Pull request merged**
