### PR TITLE
compile with QGLViewer Qt5 version

### PR DESCRIPTION
**Pull request by BorisMansencal**
*Thanks a lot for contributing to DGtal, before submitting your PR, please fill up the description and make sure that all checkboxes are checked. Please remove these lines in your PR.*

# PR Description

Fix compilation with QGLViewer Qt5 version (2.7.x and above).

According to pr #1281 it should compile with QGLViewer 2.7.0, but small changes seem to be missing. There are two references to QGLWidget in src/DGtal/io/viewers/Viewer3D.ih despite QGLViewer does not inherit from QGLWidget since 2.7.0. Besides, cmake/FindQGLViewer.cmake does not find QGLViewer-qt5 library. This PR fixes these two problems.

Tested on Ubuntu 16.04 (Qt 5.5.1) and Fedora 27 (Qt 5.9.2) with QGLViewer (2.7.0 and 2.7.1) compiled from source with DGtal, configured with:
`ITK_DIR=/tools/InsightToolkit-4.12.2/build cmake .. -DWITH_ITK:BOOL=ON -DWITH_OPENMP:BOOL=ON -DWITH_QGLVIEWER:BOOL=ON -DWITH_QT5:BOOL=ON -DBUILD_TESTING:BOOL=ON `
DGtal compiles fine both on Ubuntu 16.04 and Fedora 27 with gcc and clang. DGtal still compiles fine with QGLViewer 2.6.7 installed from packages on Fedora27. It was not tested on Windows.

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
Thanks @BorisMansencal I will look it, just after the merge of a fix for HDF5 which fails from probably a new version on hdf5.

**Comment by kerautret** [comment]
The HDF5 fix should be fine now for travis, @BorisMansencal could you please update your branch with master ?

**Comment by kerautret** [comment]
looks fine thanks a lot (also tested with DGtalTools which is fine).
Just before merging if you coud add an entry in the Changelog.md file it will be perfect. ([here](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md))

**Comment by dcoeurjo** [comment]
Can I review this one ?

**Comment by kerautret** [comment]
@dcoeurjo yes just the changelog is missing else fine for me ;)

**Comment by dcoeurjo** [comment]
THanks. Merging.

**Pull request merged**
