### PR TITLE
Patch SmartCH

### PR DESCRIPTION
**Pull request by isivigno**
Fix too restrictive asserts of methods ArithmeticalDSSConvexHull::smartCH and ArithmeticalDSSConvexHull::smartCHNextVertex to enable negative positions as input arguments.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
This PR looks fine. @isivigno, could you please merge the master of DGtal into this PR before I merge it ?

**Comment by dcoeurjo** [comment]
Hi @isivigno, could you please merge the master back ?

**Comment by isivigno** [comment]
Merged with the master, but travis fails, don't know why...

**Comment by dcoeurjo** [comment]
The problem comes from travis's bots.. no big deal.. merging.
thanks

**Pull request merged**
