### PR TITLE
Modern "flat design" for doxygen documentation

### PR DESCRIPTION
**Pull request by jlevallois**
# PR Description

This PR will change the default CSS of doxygen html export by a more modern one.

## modern-doxygen-green.css
Screenshot

## modern-doxygen-darkblue.css
Screenshot

## modern-doxygen-blue.css
Screenshot

## modern-doxygen-orange.css
Screenshot

## modern-doxygen-purple.css
Screenshot
# Checklist

- [N/A] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [N/A] Doxygen documentation of the code completed (classes, methods, types, members...)
- [N/A] Documentation module page added or updated.
- [N/A] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

:octocat:

### CODE REVIEW

**Comment by jlevallois** [comment]
(Some other themes are coming)

**Comment by kerautret** [comment]
nice @jlevallois and could have a associated  variant for DGtalTools ?

**Comment by dcoeurjo** [comment]
The idea is that one theme will be used for DGtal and another one for DGtalTools. 
Let's wait for couple of new possible CSS before we vote for the theme 

(thx again @jlevallois )

**Comment by dcoeurjo** [comment]
Thanks
I send a mail to the ML

**Comment by dcoeurjo** [comment]
My Vote:
- DGtal: blue
- DGtalTools: purple

**Comment by kerautret** [comment]
My Vote:
- DGtal: blue
- DGtalTools: green

**Comment by jlevallois** [comment]
My Vote:

- DGtal: blue
- DGtalTools: green

**Comment by troussil** [comment]
- DGtal: darkblue
- DGtalTools: blue

**Comment by naubry** [comment]
- DGtal : darkblue
- DGtalTools : green

**Comment by akrah** [comment]
- DGtal : darkblue
- DGtalTools : blue

**Comment by JacquesOlivierLachaud** [comment]
- DGtal : darkblue
- DGtalTools : purple/blue 
can we make the purple more dark bluish ?

**Comment by rolanddenis** [comment]
- DGtal: blue
- DGtalTools: green

**Comment by copyme** [comment]
- DGtal: blue
- DGtalTools: green

**Comment by dcoeurjo** [comment]
thanks. Poll ends now.

Let's go with blue (dgtal) + green  (green).

**Comment by dcoeurjo** [comment]
@jlevallois can you update the doxyfiles please ?

**Comment by dcoeurjo** [comment]
@jlevallois I'll do the PR for DGtalTools if you want

**Comment by dcoeurjo** [comment]
Merging 

:octocat:

**Pull request merged**
