### PR TITLE
Typos in blurred segment equation

### PR DESCRIPTION
**Pull request by ngophuc**
# PR Description

*your description here*

# Checklist

- [ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
Thanks ;)

**Review by kerautret — APPROVED** [review]
👍🏻

**Comment by dcoeurjo** [comment]
thanks a lot. Could you please add a new entry to the Changelog ?

**Comment by ngophuc** [comment]
Sorry, I dont understand. What I have to do exactly for the Changelog?

**Comment by kerautret** [comment]
a new entry here: https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md

**Comment by ngophuc** [comment]
Ok, done ! Thank Bertrand.

**Comment by kerautret** [comment]
> Ok, done ! Thank Bertrand.

You can edit it in this branch no ? I see another PR ;)

**Comment by ngophuc** [comment]
> > Ok, done ! Thank Bertrand.
> 
> You can edit it in this branch no ? I see another PR ;)

👍🏻

**Review by kerautret — APPROVED** [review]

**Comment by dcoeurjo** [comment]
Thanks @ngophuc 
Merging

**Pull request merged**
