### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

*your description here*

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Review by kerautret — COMMENTED** [review]
Ok for me ! 🎉 Just remove beta tag in the CMakeList.txt ?
SET(DGtal_VERSION_PATCH beta)

**Comment by dcoeurjo** [comment]
oops;)

**Review by kerautret — APPROVED** [review]
👌🏻Else did we merge the Adrien PR ?

**Comment by dcoeurjo** [comment]
I don't know, is his PR ready for merging ?

**Comment by kerautret** [comment]
> I don't know, is his PR ready for merging ?

He detect some differences when using circulator instead iterator in the tools but I think that it can just be an issue for later. I discuss with him and is ok. I am testing now if the PR on tools is ok with circulator (I merge with CLI11 on its branch)

**Review by kerautret — APPROVED** [review]

**Review by JacquesOlivierLachaud — DISMISSED** [review]

**Comment by dcoeurjo** [comment]
Ok I'll merge all the PR to see where we are (cross dependency with DGtalTools)

**Pull request merged**
