### PR TITLE
fix of Labels iterator

### PR DESCRIPTION
**Pull request by rolanddenis**
Fixing a bug on iterators over Labels that makes begin() iterator equal to end() when the first label is set.

### CODE REVIEW

**Comment by JacquesOlivierLachaud** [comment]
Fix consistent. Travis ok except for the weird recurrent bug. I merge.

**Comment by dcoeurjo** [comment]
oops too late, I have an issue with this PR: Labels must be unsigned (I don't know why the concept check  has been commented out). I'll comment later..

**Comment by dcoeurjo** [comment]
As default type: label is uint and the -1 initialization is hazardous...

**Comment by rolanddenis** [comment]
Ok. J.-O. suggested initialization with ~0. The fix is coming.

**Comment by dcoeurjo** [comment]
Wait... I also have an issue with ~0: default c++ will interpret this as "int" negate and there could be issues with the implicit cast to words... I'd use std::numeric_limits instead.. @JacquesOlivierLachaud  ?

**Comment by JacquesOlivierLachaud** [comment]
Le 10/03/2015 15:47, David Coeurjolly a écrit :
> Wait... I also have an issue with ~0: default c++ will interpret this as
> "int" negate and there could be issues with the implicit cast to
> words... I'd use std::numeric_limits instead.. @JacquesOlivierLachaud
> <https://github.com/JacquesOlivierLachaud> ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DGtal-team/DGtal/pull/971#issuecomment-78068535>.
> 
For me, ~ is a bitwise operator and does not care about integer sign.
Hence, it flips all 0 to 1 without any check.

**Comment by rolanddenis** [comment]
Ho, I thinks std::numeric_limits was from the C++11 norm ... apparently not. I agree that it is the best solution.

**Comment by rolanddenis** [comment]
I have updated PR #972 .

**Comment by dcoeurjo** [comment]
Thanks @rolanddenis !!
Sorry about that, I am have been a bit paranoiac with this implicit cast stuff...

( @JacquesOlivierLachaud  ok for ```~``` but I have the feeling that ```~static_cast<Label>(0)```would have been more secure.. again, maybe I'm crazy with that...)

**Comment by JacquesOlivierLachaud** [comment]
But numeric_limits is fine also !

**Pull request merged**
