### PR TITLE
add key Shift-L to save configuration file.

### PR DESCRIPTION
**Pull request by kerautret**
Tiny PR just to add new key to save viewing setting, usefull to compare in live two different view without the need to close the view...

### CODE REVIEW

**Comment by dcoeurjo** [comment]
is the binding  'shift-M' ? not working  on my system... what should I see when I click ?
BTW, would it be possible to add an entry in the help ?

**Comment by kerautret** [comment]
Sorry it is Shift-M.it is my fault ;(
The key is added in the help.
To test: load something displayed in 3DViewer. change the view, press Shft-L (record the viewer setting), change the view settings, and press L; it should go again on saved configuration.

**Comment by dcoeurjo** [comment]
Shift-L / L  works. What does Shift-M do ?

**Comment by kerautret** [comment]
ok, Nothing special I think. ;)

**Comment by dcoeurjo** [comment]
so it is SHIFT-L, right ? (title of the PR and the 'Sorry... ' comment)  ?

**Comment by kerautret** [comment]
yes Shift -L , sorry I change the title for history ,;)

**Comment by dcoeurjo** [comment]
ok great. Could you please just add a changelog entry ? E.g.

  - Shift-L / L key binding added to save and restore camera settings 

?

**Comment by kerautret** [comment]
yes done ;)

**Comment by dcoeurjo** [comment]
merging, thanks

**Pull request merged**
