### PR TITLE
Dev catch

### PR DESCRIPTION
**Pull request by dcoeurjo**
* Upgrade to catch develop version 
* fixing @kerautret catch test ( "&&" in REQUIRE does not compile anymore, please use separate REQUIRE)
* The dedicated Catch option is set if the  build is without CPP11.

poke @rolanddenis

### CODE REVIEW

**Comment by kerautret** [comment]
ok for the && ;) merging thanks

**Comment by dcoeurjo** [comment]
Thanks. 
@kerautret, please have a look to point vector unit test, catch also provides an automatic ```approx``` to avoid your 0.000001 constants

**Comment by kerautret** [comment]
yes I check it that's great the approx() ! I change it in AlphaThickPR

**Comment by kerautret** [comment]
thanks!

**Pull request merged**
