### PR TITLE
Fixing min=max in GradientColormap

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

This PR fixes issue #899.

# Checklist

- [n.a.] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [n.a.] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by kerautret** [comment]
great, I look it ;)

**Comment by kerautret** [comment]
thanks looks fine! (I was wondering if we add it also for HueColorMap ?)

**Comment by dcoeurjo** [comment]
(yeah we should to it for all cmap actually...)

**Comment by kerautret** [comment]
@dcoeurjo I PR on your branch the other color map fix

**Comment by dcoeurjo** [comment]
I think you have PRed the wrong branch ;)

**Comment by kerautret** [comment]
oups you are right, I do it on the good branch ;)

**Comment by dcoeurjo** [comment]
Perfect, thanks (merged to my branch)

**Comment by kerautret** [comment]
you are welcome, merging!

**Pull request merged**
