### PR TITLE
Fix missing template parameter for overloaded functions that use PointVector.

### PR DESCRIPTION
**Pull request by rolanddenis**
:tada: :beers: **Happy New Year to all the DGtal team !** :beers: :tada:

# PR Description

The hint comes from a compilation test of DGtal using Intel Compiler 17. It raises errors in display-related classes (`Display[23]DFactory`, `Viewer3DFactory`, ...) about overloaded functions/methods not found.

A minimal example is:
```C++
template < unsigned int N >
struct Container {};

template < int N, typename TContainer = Container<N> >
struct Dummy {};

template < int N >
void f( Dummy<N> const & )
{
}

int main()
{
    Dummy<2> toto;
    f(toto);
    return 0;
}
```
that fails to compile with error:
```
test.cpp(15): error: no instance of function template "f" matches the argument list
            argument types are: (Dummy<2, Container<2U>>)
      f(toto);
      ^
test.cpp(8): note: this candidate was rejected because at least one template argument could not be deduced
  void f( Dummy<N> const & )
```

The problem comes from the different integer type in template parameters (`int` versus `unsigned int`) that leads `icpc` to ignore the default `TContainer` type when searching for overloaded functions/methods.

In DGtal, it corresponds to the `Dimension` typedef that is a signed integer versus the unsigned `std::size_t` that is used to specify the size of a `std::array` (the default container for `PointVector`).

It is probably a bug since `g++` and `clang++` doesn't matter about this issue, **but anyway**, the `TContainer` template parameter is actually missing from those overloaded functions/methods in order to accept `PointVector` with non-standard value container, thus leading to this PR submission.

Intel Compiler 17 now compiles without error, but still some warnings about deprecated use of `std::binder2nd` (see #1221) and another warning about an invalid usage of `auto` (probably another bug). Version 16 still fails to compile DGtal (default options) but on a clearly valid `C++11` syntax.

# Checklist

- ~~[ ] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).~~
- ~~[ ] Doxygen documentation of the code completed (classes, methods, types, members...)~~
- ~~[ ] Documentation module page added or updated.~~
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by rolanddenis** [comment]
Where are all Travis jobs ? :scream:

**Comment by dcoeurjo** [comment]
😄 my bad... While working on MacOs bots, I've disabled linux ones...

**Comment by dcoeurjo** [comment]
and happy new year 🎉

**Comment by dcoeurjo** [comment]
travis up and running ;) can you please merge the master again?

**Comment by rolanddenis** [comment]
Done :octocat:

**Pull request merged**
