### PR TITLE
add optional .qglviewer.xml saving

### PR DESCRIPTION
**Pull request by kerautret**
and set to false by default.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Great. Maybe you can add setter/getter methods to change the variable state without recompiling (or add a key shortcut in the viewer)

**Comment by kerautret** [comment]
In fact the key_M+SHIFT call directly the save in .qglViewer and flag is myAutoSaveState ;)

**Comment by kerautret** [comment]
is public

**Comment by dcoeurjo** [comment]
Ok fine

**Pull request merged**
