### PR TITLE
Add a moveTo() function in implicit and star shapes

### PR DESCRIPTION
**Pull request by akrah**
# PR Description

Add the ability to move the shape center in `DGtal/shapes/parametric` and `DGtal/shapes/implicit` packages.

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Looks ok.. could you please add a short unit test  and a changelog entry ?

Up to you but you could also update the shape module page..

**Comment by akrah** [comment]
About the unit test, do you prefer:
- a test file per shape that test all methods of one shape?
- a test file per method that test one method for all shapes?

**Comment by dcoeurjo** [comment]
I would say a single test file for all shapes /methods.. with different test cases.

**Comment by akrah** [comment]
Travis failed with his message:

> E: There were unauthenticated packages and -y was used without --allow-unauthenticated

and these apt warnings:

> W: GPG error: http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E9377A2BA9EF27F
> W: The repository 'http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease' is not signed.
> W: There is no public key available for the following key IDs: 1E9377A2BA9EF27F  
> W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
> W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
> W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
> W: There is no public key available for the following key IDs: 6B05F25D762E3157

Is it a Travis configuration error? I think I cannot address this problem in this PR.

**Comment by akrah** [comment]
@dcoeurjo All looks good for me now.

**Comment by dcoeurjo** [comment]
allright. thx

**Pull request merged**
