### PR TITLE
Disabling examples build by default.

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Setting BUILD_EXAMPLES to OFF by default.

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug mode.
- [x] All continuous integration tests pass (Github Actions & appveyor)

### CODE REVIEW

**Review by kerautret — APPROVED** [review]
👍🏻

**Comment by dcoeurjo** [comment]
`testLongvolWriter` and `testCompressedVol` are failing on GitHub Action. I'm not able to reproduce the bug on my computers. Can someone double-check on their side? 

@kerautret @JacquesOlivierLachaud @rolanddenis

**Comment by kerautret** [comment]
Same for me I checked on my Mac and on a Debian computer and both testLongvol and testCompressedVolWriter passed...

**Comment by dcoeurjo** [comment]
Strange...

**Pull request merged**
