### PR TITLE
Fix board spherical

### PR DESCRIPTION
**Pull request by dcoeurjo**
Bugfix in quad visualization in BoardD3D and Viewer3D

### CODE REVIEW

**Comment by kerautret** [comment]
@dcoeurjo From just a test it looks that exported normals are not always near surface exterior.
I tested it from the 3DCurvatureViewer PR of Jeremy with Al.vol...

**Comment by dcoeurjo** [comment]
Sorry but I don't understand what you mean

**Comment by kerautret** [comment]
I don't know if it is related to your edit but in the export of voxel primitive the face order should be in inverted in some direction see:
capture d ecran 2015-04-01 a 08 20 37

**Comment by dcoeurjo** [comment]
which tool generates this vector field ?

**Comment by kerautret** [comment]
meshlab...

**Comment by dcoeurjo** [comment]
well.. I don't know.. elementary normal vectors to quad is something highly dependent on how you create the quads.. Can you please provide an example with a single cube ?

**Comment by kerautret** [comment]
Yes here is what we obtain from obj of a single voxel centered in 0: (the sequence is perhaps not good)
#  OBJ format
# generated from Board3D from the DGTal library
mtllib test.mtl

o  0
usemtl Mat_0
v -0.5 -0.5 0.5
v 0.5 -0.5 0.5
v -0.5 -0.5 -0.5
v 0.5 -0.5 -0.5
v -0.5 0.5 0.5
v 0.5 0.5 0.5
v -0.5 0.5 -0.5
v 0.5 0.5 -0.5
vn -1 0 0
vn 0 0 -1
vn 0 1 0
vn 0 0 1
vn 0 -1 0
vn 1 0 0
f -8//-6 -7//-6 -5//-6 -6//-6
f -8//-5 -6//-5 -2//-5 -4//-5
f -8//-4 -7//-4 -3//-4 -4//-4
f -7//-3 -5//-3 -1//-3 -3//-3
f -6//-2 -5//-2 -1//-2 -2//-2
f -4//-1 -3//-1 -1//-1 -2//-1

**Comment by dcoeurjo** [comment]
Did you send a cube or a digital surface surfel set to the board3d ?

**Comment by kerautret** [comment]
a digital point with mode paving:
aBoard << SetMode3D("PointVector", "Paving");
aBoard << Point(0,0,0);
aBoard.saveOBJ("test.obj");

**Comment by dcoeurjo** [comment]
Ok so it has nothing to do with my PR (I only change things in Quad drawing)

**Comment by kerautret** [comment]
Yes, the pb looks to be present in the  master, we perhaps have miss it in previous PR...

**Comment by kerautret** [comment]
I add an issue on that.

**Comment by kerautret** [comment]
could you update from master for merging ?

**Comment by dcoeurjo** [comment]
Done

**Comment by kerautret** [comment]
thanks , I add an issue, sorry for the false bug, waiting for travis and merging

**Comment by kerautret** [comment]
travis looks too long for some config, merging

**Pull request merged**
