### PR TITLE
Travis tweaks: documentation + osx testbuild 

### PR DESCRIPTION
**Pull request by dcoeurjo**
This PR has many commits but it was just for travis debugging. For short:
   - cleaned up configuration build on travis-ci.org
   - NEW test suite on Mac OSX (clang only). 
   - When a PR is merged, the documentation (doxygen and docset) is computed and deployed to dgtal.org/doc/nightly

### CODE REVIEW

**Comment by kerautret** [comment]
nice new feature, just have you check travis ?

**Comment by dcoeurjo** [comment]
Ok i see.. My encrypted variable has been set on my fork but not on the Organization repo.

**Comment by dcoeurjo** [comment]
Doing a self merge (travis encrypted variable is hard to debug in PR mode)

**Comment by dcoeurjo** [comment]
Done. I may commit some edits directly on the master if the build fails

**Pull request merged**
