### PR TITLE
Various warnings/deprectated fixes

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

Various warnings/deprectated/static analysis fixes

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Review by kerautret — APPROVED** [review]
Looks fine, just perhaps changelog?

**Comment by dcoeurjo** [comment]
Yep this PR is still WIP. I need to fix other warnings raised by Xcode13 ;)

**Comment by dcoeurjo** [comment]
Done for the Changelog (I'll stop here with the edits)

**Review by kerautret — APPROVED** [review]
codas is also wrong with the Changelog like for my PR but not important. Travis also but not related. Thanks !

**Comment by dcoeurjo** [comment]
I have edited codacy settings to avoid parsing the markdown. 
For Travis, I don't know what is the problem...

**Pull request merged**
