### PR TITLE
bug fixed in method getPoint of ArithmeticalDSL

### PR DESCRIPTION
**Pull request by troussil**
The bug occurred for negative values of position. It is now corrected. Tests have been added.

### CODE REVIEW

**Comment by kerautret** [comment]
@troussil can you merge from master to check travis ?

**Comment by troussil** [comment]
done, but travis stopped.

2015-01-09 14:25 GMT+01:00 Bertrand Kerautret <notifications@github.com>:

**Comment by troussil** [comment]
done again (travis stopped again)

**Comment by dcoeurjo** [comment]
got it (related to coverage computation). merging

**Pull request merged**
