### PR TITLE
fix VS contour helper

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
Fix as mentioned in PR #1381 
Not yet tested on VS, I can try next week on the PC of the dept.

# Checklist

- [x] Unit-test of your feature with [Catch](http://dgtal.org/doc/stable/moduleCatch.html).
- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Documentation module page added or updated.
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtal/blob/master/ChangeLog.md) added.
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Travis & appveyor)

### CODE REVIEW

**Comment by dcoeurjo** [comment]
thx @kerautret , can you please add a Changlog entry ?

**Comment by dcoeurjo** [comment]
@kerautret is this PR complete ?

**Comment by kerautret** [comment]
It is up to you, I have finished the VS tests but we can merge and add a new issue later, else I will be able to test perhaps tomorrow.

**Comment by dcoeurjo** [comment]
Let’s merge this one. Thanks

**Pull request merged**
