### PR TITLE
fix warning std::abs

### PR DESCRIPTION
**Pull request by kerautret**
Small PR just to remove warning appeared from last OS X update

### CODE REVIEW

**Comment by rolanddenis** [comment]
Actually, it is more than a simple warning: if both `abs` and `std::abs` are in scope, and without explicit use of `std::abs` (or of the directive `using std::abs;`), the compiler will choose `abs` that works on integers.

For example, the following code:
```C++
#include <iostream>
#include <cstdlib>
#include <cmath>

int main()
{
    double v = 2.5;
    std::cout << "abs(2.5) = " << abs(v) << std::endl;
    std::cout << "std::abs(2.5) = " << std::abs(v) << std::endl;
    return 0;
}
```
compile silently with `g++` (v4.9.1 on Linux), even with `-Wall -Wextra`, and with a warning with `clang++` (v3.5.0):
```
test.cpp:8:35: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
    std::cout << "abs(2.5) = " << abs(v) << std::endl;
                                  ^
test.cpp:8:35: note: use function 'std::abs' instead
    std::cout << "abs(2.5) = " << abs(v) << std::endl;
                                  ^~~
                                  std::abs
1 warning generated.
```

 but both binaries output is:
```
abs(2.5) = 2
std::abs(2.5) = 2.5
```

I've made a fast search through the DGtal source and it seems to be the only file where abs (alone) is used on floats.

**Comment by kerautret** [comment]
yes,  I also detects strange behavior with abs in my dev prog ;)

**Comment by dcoeurjo** [comment]
Thanks @kerautret for the PR and @rolanddenis for the explanation :)

**Comment by dcoeurjo** [comment]
@kerautret could you please merge the master to this branch?

**Comment by kerautret** [comment]
ok

**Comment by kerautret** [comment]
@dcoeurjo done

**Comment by dcoeurjo** [comment]
merging.

**Pull request merged**
