### PR TITLE
Boost include fix in DGtalConfig.cmake

### PR DESCRIPTION
**Pull request by dcoeurjo**

### CODE REVIEW

**Comment by rolanddenis** [comment]
Congrats, you made `clang` segfault with only one line added :beers:

**Comment by dcoeurjo** [comment]
Yep but what a line.... :smile:

**Comment by rolanddenis** [comment]
How did you manage this ? Travis modification ?

**Comment by dcoeurjo** [comment]
nope I just  restarted the travis build.. (restart button on travis)
the problem was related to the VM system I guess

**Comment by dcoeurjo** [comment]
Doing a self-merge.

**Pull request merged**
