### PR TITLE
Improved raw io

### PR DESCRIPTION
**Pull request by elcerdo**
#1007 and #1008 must be merged first.

### CODE REVIEW

**Comment by dcoeurjo** [comment]
I'll review but why you didn't branch the current master ?
#1007 and #1008 are not needed here

**Comment by elcerdo** [comment]
i needed both the new raw io and the new DEC version in my private repository.

**Comment by dcoeurjo** [comment]
In your private repo, you could have merged 2 branches instead. Your approach does not allow parallel reviews of PR.

**Comment by elcerdo** [comment]
sorry for that.
next time i will pay more attention.

**Comment by dcoeurjo** [comment]
Can you please check travis issues ? 
(some are related to raw IO)

**Comment by dcoeurjo** [comment]
Sorry for the delay. Thanks @elcerdo 
can you please add an entry to the changelog ?

**Comment by elcerdo** [comment]
ok to merge from my POV

**Comment by dcoeurjo** [comment]
great thanks.

**Pull request merged**
