### PR TITLE
Fix Issue 1013

### PR DESCRIPTION
**Pull request by rolanddenis**
- Fixing issue #1013 by using new parameters list when QGLViewer has version >= 2.5.0 (see change-log http://libqglviewer.com/changeLog.html);
- Cleaning code (trailing spaces and mixed tab/space indentation).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Thanks for the fix! 
merging

**Comment by dcoeurjo** [comment]
oops.. I can't merge it as it is.. can you please merge the master to this branch ?

**Comment by rolanddenis** [comment]
Fixed ;)

**Comment by dcoeurjo** [comment]
:) Thanks..

**Pull request merged**
